# Generated by Django 5.0.1 on 2024-01-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortUrl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='shortlink',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
